# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-27 00:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rsvp',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
