# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-27 00:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0002_rsvp_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsvp',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
    ]
