# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-27 00:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nashville', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='author',
            field=models.CharField(choices=[(1, 'Adam Wallace'), (2, 'Morgan Hunter')], max_length=20, unique=True),
        ),
    ]
