# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-27 01:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nashville', '0002_auto_20180326_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='author',
            field=models.CharField(choices=[('ADAM WALLCE', 'Adam Wallace'), ('MORGAN HUNTER', 'Morgan Hunter')], max_length=20, unique=True),
        ),
    ]
