# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-27 01:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nashville', '0003_auto_20180326_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='header',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='guide',
            name='short_description',
            field=models.TextField(max_length=150, unique=True),
        ),
    ]
