# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-27 01:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nashville', '0004_auto_20180326_2003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guide',
            name='location',
        ),
        migrations.AddField(
            model_name='guide',
            name='address',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guide',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
