# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-27 01:32
from __future__ import unicode_literals

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('nashville', '0005_auto_20180326_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='image',
            field=image_cropping.fields.ImageCropField(upload_to='Blog_image'),
        ),
    ]
