# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-27 01:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nashville', '0006_auto_20180326_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='image',
            field=models.ImageField(upload_to='Guide_image'),
        ),
    ]
