# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-27 02:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nashville', '0007_auto_20180326_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='body_2',
            field=models.TextField(default='Sample'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guide',
            name='favorite_quote',
            field=models.CharField(default='Sample', max_length=100),
            preserve_default=False,
        ),
    ]
