# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-27 03:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nashville', '0008_auto_20180326_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='cost',
            field=models.CharField(default='$10 - $20', max_length=30),
            preserve_default=False,
        ),
    ]
